### ISSUE TITLE
Run on an IP other than 127.0.0.1

### ISSUE THREAD

**Issue by djfarrelly** [djfarrelly/MailDev#11]
i.e. 192.168.x.x

**Comment by Seidr** [comment]
I'm looking into this - should be simple enough for the web server, however the SMTP server may require a pull request to simplesmtp to resolve. Not sure if it's worth waiting for simplesmtp to be replaced to implement this?

**Comment by Seidr** [comment]
Just had a quick look at simplesmtp - looks like the listen export will support changing of the host on the current version. I'll get a pull request in shortly for this :)
