### ISSUE TITLE
Add an option to display attachments directly in the message preview

### ISSUE THREAD

**Issue by samy** [djfarrelly/MailDev#114]
When you click on a message to display its contents, you cannot directly know if there are any attachment, and you must click on "Attachments" menu item.

It should be useful to have the ability to display attachments directly in the preview zone

**Comment by oktapodia** [comment]
This feature has been added a while ago, I'm closing it now, sorry for the delay

**Comment by vintesoft** [comment]
@oktapodia I can't get attachments display by default. Which options should I issue to get this?
