### ISSUE TITLE
Ability to forward email to real recipient

### ISSUE THREAD

**Issue by josser** [djfarrelly/MailDev#121]
Hi! 
It would be great to have ability to forward email to real recipient after viewing it in web UI to check how it looks in real mail-client. I know about this cool feature "download .eml" but forward is just a bit easier. 

Thank you for your work and sorry for my bad english :)

**Comment by djfarrelly** [comment]
Hi @josser, MailDev supports forwarding your emails to real clients if you authenticate with an outgoing service. Check out the docs here: https://github.com/djfarrelly/MailDev#outgoing-email

You can then relay your email to the email address manually with the Relay button or setup auto-relay:
![screenshot](https://www.dropbox.com/s/k93mnb55ejtugvr/Screenshot%202016-05-17%2013.11.47.png?dl=1)
