### ISSUE TITLE
Messages with tag-like content don't display

### ISSUE THREAD

**Issue by AgDude** [djfarrelly/MailDev#130]
When I send a message like the following it does not display in either text or html mode. I can view the source.  This seems to be due to the use of angle brackets (`< >`). I am using version 0.13.4.

The source is:

```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: mysubject
From: me@example.com
To: me@somewhere.com
Date: Wed, 20 Jul 2016 13:55:22 -0000
Message-ID: <20160720135522.3757.27067@ip-10-1-112-42.ec2.internal>

<User: SomeOne alias) something>
```

**Comment by djfarrelly** [comment]
Hey @AgDude, sorry for the delay. This may be related to how the email is being parsed by [`MailParser`](https://github.com/andris9/mailparser), I'll have to try to write a test for this one when I have some time, if you're able to dig into this perhaps that is a place to start 😄
