### ISSUE TITLE
Documentation update? - Rails, docker, host, SSL

### ISSUE THREAD

**Issue by ramontayag** [djfarrelly/MailDev#135]
I couldn't connect to localhost 25.
1. I had linked the `mail` service to the `web` service:

``` yml
  web:
    #...
    links:
      - mail
```
1. I setup my development.rb:

``` rb
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    :address => "localhost",
    :port => 25,
  }
```

But when I'd send mail, I kept getting errors where the app couldn't connect to port 25. I changed the `:address` option to `mail`, since `links` provides that hostname, and got this error instead:

> OpenSSL::SSL::SSLError - hostname "mail" does not match the server certificate:

I added the following to the `smtp_settings` and got the email to go through:

``` rb
    :openssl_verify_mode  => 'none',
```

Does the above look correct? Should I have been getting the error with `localhost` in the first place?

**Comment by paulsturgess** [comment]
I just hit this same certificate issue and adding `openssl_verify_mode: 'none'` resolved it for me.

**Comment by teoulas** [comment]
If you don't mind overriding the command in your docker-compose.yml you can use this command-line argument:
```yaml
maildev:
  command: bin/maildev --hide-extensions STARTTLS
```
It's not documented, but it's easy to [find it in the code](https://github.com/djfarrelly/MailDev/blob/master/index.js#L40-L41).

**Comment by oktapodia** [comment]
Sorry it's been a long time ago, the documentation has been added for that specific part. I'm closing it.
