### ISSUE TITLE
Attachments overwriting each other

### ISSUE THREAD

**Issue by cbdabner** [djfarrelly/MailDev#145]
Using 0.14.0, it looks like emails with the same content, and same named attachments are saving the attachments over the top of each other.

I had a brief look and is this due to using `contentId` instead of `generatedFileName` from MailParser's attachment properties? I can check myself when I get a chance, but thought I'd raise it first either way.

**Comment by cdolivet** [comment]
I just faced the same issue with emails having the same content and same named attachments that return the same attachements content even if the email source code show different base64 content.

**Comment by arnou** [comment]
Same issue in 1.0.0-rc2

**Comment by kgeis** [comment]
@cbdabner, I agree that `contentId` should be used instead of `generatedFileName`.

Evidenced by the comments from @cdolivet and @arnou, the attachments are not being overwritten, but the code to find the attachment just picks the first match by filename.
