### ISSUE TITLE
how to send and receive mails?

### ISSUE THREAD

**Issue by suriyaJaay** [djfarrelly/MailDev#149]
hi

could anyone tell me how to configure it for sending and receiving mails?

read document but am unable to understand the it

and also my smtp has running on :1025. but if i try to navigate from brower it show "page is not working"

i might understand very wronly.. kindly some guide me 
thank you

**Comment by OliverFischer** [comment]
Hi, 

use something like nodemailer sending emails. Very handy and easy to use. Create an smtp config with nodemailer like 
```json
smtpConfig = {
            port : 1025,
            ignoreTLS : true
        }
```
and install maildev globally by npm i -g maildev.
Stop any smtp on port 1025 and start maildev. 

If you now sen mails via nodemailer yu should be able to view the sent mail in the inbox on localhost:1080
