### ISSUE TITLE
Does not process SIGINT properly

### ISSUE THREAD

**Issue by jsonxr** [djfarrelly/MailDev#156]
When running via docker command line, it does not shut down when I press "CTRL-C".  

    docker run --name=mail --rm -p "1080:80" -p "25:25" djfarrelly/maildev

I have to type:

    docker rm -f mail

To force it to shut down.

Adding 

    process.on('SIGINT', process.exit); // Handle ctrl-c when running via docker run
    process.on('SIGTERM', process.exit); // Handle when we docker rm the container

To bin/maildev would handle this

**Comment by jsonxr** [comment]
Pull request to fix:
https://github.com/djfarrelly/MailDev/pull/157

**Comment by djfarrelly** [comment]
I have a feeling that this is happening because the connections are staying open, possibly with Socket.io. I'm looking into this.
