### ISSUE TITLE
Crashes when smtp port set to anything below 1024

### ISSUE THREAD

**Issue by realjax** [djfarrelly/MailDev#159]
MailDev app running at 0.0.0.0:1080
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:1023
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

**Comment by donut87** [comment]
Just from the top of my head...
Do you have the permission to use this port? Try running maildev as root?

**Comment by realjax** [comment]
Haven't tried as far as I can  remember. But it shouldn't crash nonetheless.

Christian Dohnert <notifications@github.com> schreef op 18 maart 2017 17:02:10 CET:
>Just from the top of my head...
>Do you have the permission to use this port? Try running maildev as
>root?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/djfarrelly/MailDev/issues/159#issuecomment-287555396

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by donut87** [comment]
I've just confirmed your problem and my theory. Yes if you run this as root, port 1023 will work just fine. Except if the port is taken. I also think you are right. This should end gracefully and not shut down with a strange looking error message, but with some useful information (could not bind port X). Maybe I'll be able to do fix this in the next days.

**Comment by realjax** [comment]
Cool, thanks!

Christian Dohnert <notifications@github.com> schreef op 18 maart 2017 23:16:33 CET:
>I've just confirmed your problem and my theory. Yes if you run this as
>root, port 1023 will work just fine. Except if the port is taken. I
>also think you are right. This should end gracefully and not shut down
>with a strange looking error message, but with some useful information
>(could not bind port X). Maybe I'll be able to do fix this in the next
>days.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/djfarrelly/MailDev/issues/159#issuecomment-287578834

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by donut87** [comment]
Can we close this now?

**Comment by realjax** [comment]
Yep, thanks

Christian Dohnert <notifications@github.com> schreef op 26 mei 2017 09:48:55 CEST:
>Can we close this now?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/djfarrelly/MailDev/issues/159#issuecomment-304216204

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
