### ISSUE TITLE
MailDev crashes on failed smtp relay

### ISSUE THREAD

**Issue by chines** [djfarrelly/MailDev#161]
Hello,

In testing MailDev with several internal mail servers to get the relay functionality working (and not knowing the correct settings all the time), I noticed that if the settings were not correctly matched to the relay mail server, it would throw errors such as the ones below and then crash (or no longer be running):

Would it be possible to handle these gracefully so that they do not bring down MailDev?

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:465
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNRESET 10.1.22.10:465
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)

**Comment by donut87** [comment]
This should definitely be handled. What do you suggest? Turning off the relay function and notify (aka write a log message) the user? Or would it be better if this was logged every time a mail was tried to send?

**Comment by chines** [comment]
log everytime.  We utilize maildev in 10 different environments, each with 10+ app servers that are sending, so a one time turn off and notify may get missed by the QA user who is using it at the time or someone troubleshooting it by testing it and seeing what happens in the log.

**Comment by oktapodia** [comment]
Looks like this one has been fix, I'm closing it.
