### ISSUE TITLE
Broken JS on CentOS7 fresh install

### ISSUE THREAD

**Issue by bugdebug** [djfarrelly/MailDev#174]
Does not work on freshly installed CentOS7.
yum install npm
npm install -g maildev
Result looks like this:
<img width="722" alt="2017-05-10 16 56 48" src="https://cloud.githubusercontent.com/assets/8185065/25902230/ade828e0-35a1-11e7-8b67-817adc1ef419.png">

**Comment by djfarrelly** [comment]
Thanks for reporting this @bugdebug! This is now fixed in the 1.0.0-rc2 release just pushed to npm!
