### ISSUE TITLE
basepath failing when looking for socket.io

### ISSUE THREAD

**Issue by ObjectiveTruth** [djfarrelly/MailDev#176]
Hey there,

I used the `--base-pathname` and all the links works except when searching for the socket.io files

<img width="279" alt="screen shot 2017-05-25 at 11 53 29" src="https://cloud.githubusercontent.com/assets/1545001/26458334/e7b20992-4140-11e7-89ac-4043d582d071.png">

I believe the issue and fix is described here, of adding the `basepath` information to the `require` call of **socket.io**

https://stackoverflow.com/questions/12824612/change-socket-io-static-file-serving-path

I'll try and submit a PR soon if I get time, but just letting y'all know

**Comment by djfarrelly** [comment]
Thanks @ObjectiveTruth! Good catch :) If you have time please ping me on the PR!

**Comment by ObjectiveTruth** [comment]
^ gotchu fam 👍

**Comment by ObjectiveTruth** [comment]
@djfarrelly Can we merge this?
