### ISSUE TITLE
Send mail with nodemailer from docker container

### ISSUE THREAD

**Issue by mikamboo** [djfarrelly/MailDev#177]
Hi @djfarrelly !

I discover MailDev project during a search on google about nodemailer. 
Would you help me to find how to sen emails with nodemailer fron insider docker container ? 

I try this the code on my local machine it's works fine. But inside a docker container on remote server, the mail is not sent. I have a succes message in the log. It seems that email message cannot go outside contaner. 

```js
'use strict';
const nodemailer = require('nodemailer');

// create reusable transporter object using the default SMTP transport
let transporter = nodemailer.createTransport({
    type: 'smtp',
	host: 'smtp.my-domaine.com',
	port: 465,
	secure: true,
	tls: {
		rejectUnauthorized: false
	},
    auth: {
        user: 'user@my-domaine.com',
        pass: 'xxxxxxx'
    }
});

// setup email data with unicode symbols
let mailOptions = {
    from: '"Fred Foo ??" <foo@blurdybloop.com>',
    to: 'my-user@gmail.com', 
    text: 'Hello world ?'
};

// send mail with defined transport object
transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
    console.log('Message %s sent: %s', info.messageId, info.response);
});
```

S o i try to link with MaildDev container an use env var like you suggested same result. no mail sent.

Any idea ?

**Comment by stguitar** [comment]
@mikamboo I would suggest SSH'ing the host machine, and then SSH into the running container so that you can run some simple telnet commands to tests connectivity from the container to the host/port you have configured in the code.  

I am running a very similar setup and not having issues with this at all (however I am fighting TLS issues at the moment)

**Comment by stguitar** [comment]
@mikamboo Oh, and you can SSH into your live contianer with:

docker exec -it <container_id> /bin/bash

This does assume that the node application is running in a linux based system that has /bin/bash on it, like Ubuntu

**Comment by mikamboo** [comment]
Hi Steven !

I finally found the solution : update y docker daemon.

I was on docker 1.11 on my server. Send mails with nodemailer with this old
version seems not works correctly.
I mouted a new vps with docker 17 et then everything works !

Thanks for the reply.



[image: About Me]

Michael PAMBO OGNANA
Software Engineer
[image: https://]about.me/michaelpamboog
<https://about.me/michaelpamboog?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>



2017-06-14 18:25 GMT+02:00 Steven Guitar <notifications@github.com>:

**Comment by amolkhanorkar** [comment]
Hi Guys, 
I'm facing the same issue. Right not running docker container on ECS cluster and one of our functionality trying to send mail using "nodemailer" node module to the users but it it not able to send mail. 
Here is the snippet which we are using,
_const sender = 'no_reply@xyz.com';
let transporter = _mail.createTransport({_
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,	
  auth: {
    user: 'no_reply@xyz.com',
    pass: 'password123'
  },
});_ 
Even, tried by opening outgoing port on security group still facing same issue. 
Please help solving issue.

Thanks,
Amol
