### ISSUE TITLE
v1.0.0-rc3 doesn't seem to work on Windows, but v1.0.0-rc2 does work

### ISSUE THREAD

**Issue by ngyikp** [djfarrelly/MailDev#185]
Node v8.1.3
Windows 7

The socket.io library can't be found on the new version, not sure what's going on, https://github.com/djfarrelly/MailDev/commit/66d071ed806f063a894dccdae60870eb938461e3 seems to be the likely culprit

Done some more testing on v1.0.0-rc2, running `maildev --base-pathname "/a/"` on Windows is broken, but running it on my Mac works 🤔

![](https://user-images.githubusercontent.com/6135313/27988529-349f601e-6456-11e7-9289-dca22771f416.png)

**Comment by apydo** [comment]
1.0.0-rc2 works fine for me on Windows 7 64bit and Node 8.1.4. RC3 fails.

**Comment by apydo** [comment]
In lib/web.js file on line 87 we can read:
`  io = socketio({ path: path.join(basePathname, '/socket.io') })`
path.join() function returns paths with backslashes on Windows (by default '\socket.io'), so the url path is incorrect.
If you want to use path.join() and get the same path on all systems you should use the posix implementation:
`  io = socketio({ path: path.posix.join(basePathname, '/socket.io') })` -> By default '/socket.io'

**Comment by hichxm** [comment]
Pull request: #204

**Comment by mcs** [comment]
Any chance this fix will be released, at least with an RC4? :pray:

**Comment by hichxm** [comment]
I dont know last commit 28 December 2017 🤷🏻‍♂️ but many many pull request as pushed to fix it
