### ISSUE TITLE
socket.io issue

### ISSUE THREAD

**Issue by vurumadla** [djfarrelly/MailDev#189]
hi i am using maildev server for sending mails. I am getting this issue for socket.io. Can anyone help on this.

Uncaught ReferenceError: io is not defined
    at app.js:18
    at Object.d [as invoke] (angular.js:3634)
    at angular.js:3483
    at Array.forEach (<anonymous>)
    at q (angular.js:300)
    at Yb (angular.js:3483)
    at c (angular.js:1294)
    at Xb (angular.js:1309)
    at Rc (angular.js:1258)
    at angular.js:20277

**Comment by vurumadla** [comment]
hi guys... can anyone respond on the above issue

**Comment by Happykiller** [comment]
I have the same issue

**Comment by ugho49** [comment]
Please fix this issue ...

**Comment by Johann-S** [comment]
To fix that issue on my PC I downloaded socket.io.js here : https://cdnjs.com/libraries/socket.io and moved it to maildev's folder
