### ISSUE TITLE
421 you talk too soon in docker

### ISSUE THREAD

**Issue by y0sh1** [djfarrelly/MailDev#194]
Hi,
Great project you've created. I have some good cases where i can make good use of this. The only problem i am currently facing is that i cannot connect to the smtp side of the docker container to submit mail.

When testing this with telnet, the connection gets killed after the first command with a 421 you talk too soon message.

When doing this within the container everything is fine and works as expected.

Am i doing something wrong? I did follow all the steps from the guide.

**Comment by StShadow** [comment]
same here

**Comment by rm-jawengo** [comment]
I had the same problem with other containers (psql dababase). So you have to implement a "wait-for" script. You will find a good example here: https://docs.docker.com/compose/startup-order/ 

the main part is written in docker-compose file: 

```
depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
```

Like this, the depending container will be started after your base container is fully running.

Hope that helps!

**Comment by berkeleybross** [comment]
Not sure if this is related, but I was struggling to get this to work in docker-compose even though it worked fine when running `docker run -p 1080:80 -p 1025:25 djfarrelly/maildev`. I solved it by changing the ports being run on with the following docker-compose.yml

`version: '3'
services:
  maildev:
    image: djfarrelly/maildev
    ports:
    - 1025:1025
    - 1080:1080
    command: ["bin/maildev", "--web", "1080", "--smtp", "1025"]
`

**Comment by oktapodia** [comment]
Looks like the @rm-jawengo message resolve the problem, closing for now.
