### ISSUE TITLE
Allow setting default options

### ISSUE THREAD

**Issue by rightaway** [djfarrelly/MailDev#198]
I'd like to request a feature to pass some default options to maildev. I'd like to set the default Display type to `Source`, and I'd like to set the default date format in the email listing on the left to `YYYY-MM-DD HH:mm:ss`.

**Comment by kgeis** [comment]
Hi @rightaway. Thanks for the ideas. Could I ask you to refile these as separate issues for better tracking and discussion?

We're working on shipping 1.0, and after that we can start looking into new features like these.

**Comment by oktapodia** [comment]
No answer from the author, I'm closing it
