### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by ianwalter** [djfarrelly/MailDev#211]
Hi, thank you for this amazing project.

I'm trying to make a request to the HTTP API to get emails in a Cypress test (in Chrome) and I'm hitting a CORS error since there's no Access-Control-Allow-Origin header. Would you accept a PR to add a configuration property to allow users to control this or since MailDev is not meant for production, perhaps we can just modify the server to accept `*`?

**Comment by oktapodia** [comment]
Thank you for your issue, feel free to do the PR :)
