### ISSUE TITLE
No docker tag for version 1.0.0-rc3

### ISSUE THREAD

**Issue by ypereirareis** [djfarrelly/MailDev#213]
Hi,
Please add a docker image with tag `djfarrelly/maildev:1.0.0-rc3` !
Thanks

**Comment by djfarrelly** [comment]
@ypereirareis a new 1.0.0 image has been pushed to Docker hub - thanks!

**Comment by kgeis** [comment]
@djfarrelly, if you just pull "djfarrelly/maildev", you don't get the 1.0.0 release. Could you also push it with the "latest" tag?
