### ISSUE TITLE
Where are emails temporarily stored?

### ISSUE THREAD

**Issue by mkweick** [djfarrelly/MailDev#216]
For all incoming emails received, where are they temporarily stored while service is running? Are they stored in memory only? In a flat file? Or some temporary directory with files for each email?

**Comment by EricAtHaufe** [comment]
On my windows machine, the email are stored:
C:\\Users\\*******\\AppData\\Local\\Temp\\maildev\\5876\\C6wLpFdQ.eml

**Comment by oktapodia** [comment]
All the emails are stored into the temp directory
