### ISSUE TITLE
I need could configure outlook to send emails

### ISSUE THREAD

**Issue by cocodrino** [djfarrelly/MailDev#219]
Hi good day, I need configure my outlook for connect to maildev, because the users will be write some emails and then, in the server, I'll capture these and apply a process....unfortunately I can't connect maildev with outlook...do you know how can I configure this??? hope you can give me a guess because I've tried several ways and I was not able to send emails to maildev using outlook...

thank you so much

**Comment by oktapodia** [comment]
Sorry it's been a long time ago, can you please explain in detail what do you want to achieve?

**Comment by cocodrino** [comment]
Hi, I ended using other library that works for that project, I'll close the issue
