### ISSUE TITLE
Failed to open attachment with # character

### ISSUE THREAD

**Issue by nisuhw** [djfarrelly/MailDev#221]
When I tried to open email's attachment that contains '#' (e.g 'number # one.txt'), I got file not found response.
![image](https://user-images.githubusercontent.com/3644433/42131023-b47f558e-7d21-11e8-9877-ad9afb1159e1.png)
![image](https://user-images.githubusercontent.com/3644433/42131020-867bacd2-7d21-11e8-8e1d-b9c1bc935afc.png)

**Comment by kgeis** [comment]
This looks like it should be easy to fix.
