### ISSUE TITLE
Crash when receive messages from Prometheus Alert Manager

### ISSUE THREAD

**Issue by blndev** [djfarrelly/MailDev#222]
Test Project: [https://github.com/blndev/prometheus-playground/tree/analyse_mailserver_crash](https://github.com/blndev/prometheus-playground/tree/analyse_mailserver_crash)

Clone and start with `./createPlayground.sh`

To force the issue just deactivate node2 with `docker-compose stop node2` and wait 5 minutes. Then the Alertmanager try to send a message and the MailDev Service shutdown without any comment.

Message (docker log):
`mailserver_1    | Recieved shutdown signal, shutting down now...`

If the branch is already removed you can validate it with the following commit: 9951017833a442fd6d059ec6394b6564ba216cf8

**Comment by oktapodia** [comment]
Can you please create a little example to easily reproduce the problem?

**Comment by philippklemmer** [comment]
I do have the same problem with keycloak. Whenever i want to test the connection it fails and maildev crashes. 

```
Could not start mail server on undefined:undefined
Port already in use or insufficient rights to bind port
Recieved shutdown signal, shutting down now...

```

**Comment by oktapodia** [comment]
@philippklemmer I think this is a different issue, your one is saying that it `Port already in use or insufficient rights to bind port`, which version did you use?

**Comment by philippklemmer** [comment]
1.0.0

**Comment by gregorskii** [comment]
Same issue here with laravel.

**Comment by oktapodia** [comment]
A new version has been published, if your port is free of use, you should be able to run it.

Closing this one for now as the subject is slightly different than the original one, feel free to create an issue if needed
