### ISSUE TITLE
Simulating delivery error

### ISSUE THREAD

**Issue by dachinat** [djfarrelly/MailDev#225]
Hi. I'm in a situation where I need to test unsuccessful deliveries. Any thoughts on simulating errors on mail receive at Nodemailer smtp server side?

Do you think calling

`callback(new Error('Simulate err');)`

in `onData` will work? Better ideas?

Thanks.

**Comment by dachinat** [comment]
Closing as of no comments for a week.

**Comment by kgeis** [comment]
When I read the subject, I thought this was a feature request, not a question. I would like to have a feature where failure modes can be configured.
