### ISSUE TITLE
Is it possible to read a gmail inbox with MailDev?

### ISSUE THREAD

**Issue by Jtech42** [djfarrelly/MailDev#227]
I don't see a way to authenticate and connect to a gmail inbox? How do I set the incoming host for authentication?

const maildev = new MailDev({
  smtp: 1025, // incoming SMTP port - default is 1025
  outgoingHost: 'smtp.gmail.com',
  incomingUser: 'jason*****com',
  incomingPass: '******'
});

**Comment by kgeis** [comment]
The incoming host is always the host that MailDev is running on. Using MailDev as a client to read from an external inbox is out of the scope of this project.

**Comment by Jtech42** [comment]
Sorry about that yep, this is not useful for reading a gmail inbox. I had another developer tell me to try this but I think he was mistaken about what I was working on.

I used imap to read an email inbox from gmail FYI to anyone searching.
