### ISSUE TITLE
socket.io missing when installed from npm

### ISSUE THREAD

**Issue by othman-fayed** [djfarrelly/MailDev#228]
Uncaught ReferenceError: io is not defined.
Web client not working.

**Comment by kgeis** [comment]
This is fixed on the release-1.0 branch, which is yet to be merged to master and pushed to npm.

**Comment by RinkAttendant6** [comment]
Is there any timeline/roadmap for the release of version 1.0?

**Comment by oktapodia** [comment]
Should be fix now ;)
