### ISSUE TITLE
Start asset url's with a slash.

### ISSUE THREAD

**Issue by arjanfrans** [djfarrelly/MailDev#235]
I have multiple maildev instances behind a proxy, that does proxying for multiple stage/test environments. The url to the instances look like this:

example.com/environment-1/maildev/
example.com/environment-2/maildev/

This works if the url ends with a slash. But if I leave out the slash, it tries to load the assets relative to `example.com/environment-2`. I believe the easy fix for this would be to start the css/js url's with a slash.

**Comment by kgeis** [comment]
It seems to me that if you start the asset URLs with /, it will load them relative to example.com/.
