### ISSUE TITLE
FEATURE REQUEST: ask it to stop

### ISSUE THREAD

**Issue by gsboil** [djfarrelly/MailDev#240]
Great product, I often use it when maintaining apps that email out.
Which means that I often end up with a script to build, spin up a few things (including maildev), and spin up the app in something like Tomcat or Wildfly. 
Then I have a separate script to stop things. So being able to stop maildev from the command like would be great - even a REST call that I could hit via curl would work.
For me, this would be a very nice nice-to-have. But it's your code, thus your call.

**Comment by kgeis** [comment]
Please add more detail to your request, like what you are trying to accomplish by asking MailDev to stop and how you would ask it to stop (like where in the UI).

**Comment by gsboil** [comment]
Asking MailDev to stop running.
And the usecase is me running a script, so the user interface is something like bash, (powershell for the winfolk, I suppose) - something I can do on the command line. Maybe something like "maildev -stop"

**Comment by kgeis** [comment]
Is there a reason not to just kill it? Like `pkill -f 'node bin/maildev'`?

Me, I might put a service wrapper around MailDev so that it can be started/stopped in a OS-idiomatic fashion.

**Comment by gsboil** [comment]
>Is there a reason not to just kill it? Like pkill -f 'node bin/maildev'?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaah........

no. no reason. thanks for your time.
