### ISSUE TITLE
Nothing in web interface

### ISSUE THREAD

**Issue by oliviermeunier** [djfarrelly/MailDev#241]
Hello,

I'm on windows 10 and I use Laragon, nothing on the web interface when sending emails via symfony. Config smtp://localhost:1025, with -v option the console said "saving email : [email text]", but the web interface is blank. Any idea ?

**Comment by eharrow** [comment]
See https://github.com/djfarrelly/MailDev/issues/201

**Comment by kgeis** [comment]
Closing as duplicate of #201.
