### ISSUE TITLE
feature request: show total email count for the view

### ISSUE THREAD

**Issue by dr4Ke** [djfarrelly/MailDev#251]
It would be nice to see how many messages there are in the inbox, or selected by the filter.
An unread count could be useful too.

**Comment by dr4Ke** [comment]
I just realized the unread count is already present in the navigator title. It should appear in the page too, along with the total (and filtered) count.

**Comment by nsorosac** [comment]
It would be nice to add this count in the favicon, very useful when you "pin" your browser tabs like this : 

![image](https://user-images.githubusercontent.com/54878/60101925-f1248a80-975c-11e9-9790-60ad6282a0a2.png)
