### ISSUE TITLE
Release a new version since dependencies have been upgraded

### ISSUE THREAD

**Issue by mDibyo** [djfarrelly/MailDev#257]
Since the v1.0.0 release (thanks for all the work on that!), a number of dependencies have been upgraded.

It would be awesome if a new version was released with the updated dependencies.

**Comment by SSANSH** [comment]
+1,  I would like also updated dependencies, currently npm audit raised to many security issue for this package.

**Comment by SSANSH** [comment]
you have simply to bump this package (expect require more work).
    Bump version:
      - express from 4.16.4 to 4.17.1
      - commander from 2.19.0 to 2.20.0
      - async from 2.6.2 to 3.1.0
      - opn from 5.5.0 to 6.0.0
    dev:
      - mocha from 6.0.2 to 6.1.4
      - node-sass from 4.11.0 to 4.12.0
      - nodemailer from 5.1.1 to 6.2.1
      - nodemon from 1.18.10 to 14.1.1
      - nyc from 13.3.0 to 14.1.1
      - standard from 10.0.2 to 12.0.1

**Comment by SSANSH** [comment]
https://github.com/djfarrelly/MailDev/pull/259

**Comment by SSANSH** [comment]
@here ?

**Comment by SSANSH** [comment]
@here Can I have a new version please?
