### ISSUE TITLE
Replace simplesmtp as SMTP server

### ISSUE THREAD

**Issue by djfarrelly** [djfarrelly/MailDev#30]
simplesmtp is deprecated and will not be Node 0.12 compatible, ~~we need to switch to Haraka: https://github.com/baudehlo/Haraka~~

**Edit:** We could also switch to https://github.com/substack/node-smtp-protocol and https://github.com/andris9/smtp-connection, Haraka is a bit complicated for what the project needs

**Comment by djfarrelly** [comment]
Found an example gist that could help: https://gist.github.com/steffenmllr/cb3d3af13d0263adf268

**Comment by djfarrelly** [comment]
From basic testing...it seems that MailDev is still working running on the latest [io.js](https://github.com/iojs/io.js) 1.0.0 alpha. We may have more time!

**Comment by djfarrelly** [comment]
Since Andris has now created [smtp-server](https://github.com/andris9/smtp-server) in addition to [smtp-connection](https://github.com/andris9/smtp-connection), I think this switch might be *way* easier to do! Combining those two to replace simplesmtp seems like the best plan here.

**Comment by Seidr** [comment]
@djfarrelly I'm going to do some playing at lunch today, and see how close I can get it to the current feature set. *takes a deep breath*
