### ISSUE TITLE
FYI: MailDev on Docker Hub

### ISSUE THREAD

**Issue by adamc00** [djfarrelly/MailDev#45]
Hello Dan. We just wanted you to know that we have pushed an image of MailDev to https://registry.hub.docker.com/u/stratdat/maildev/ since I couldn't find one there already. Thanks for your work, we found it last week and are already using it in two projects with great success.

**Comment by djfarrelly** [comment]
Wow @adamc00, thanks for this, so great to see it on Docker hub!
I'm going to push out #46 on a 0.7.0 release today or tonight. Then you'll be able to use the master branch of this repo for the Docker Hub and get all of the updates!

**Comment by djfarrelly** [comment]
Update: 0.7.0 is out: https://www.npmjs.com/package/maildev

**Comment by adamc00** [comment]
Thanks Dan! I've just updated the Docker image to 0.7.0 using your repo directly.
