### ISSUE TITLE
Add optional authentication for web GUI

### ISSUE THREAD

**Issue by pkat** [djfarrelly/MailDev#47]
It would be great if we could have optional basic auth implemented so that access could be restricted on dev servers for example.

**Comment by djfarrelly** [comment]
Hey @pkat! That's a cool idea, I could see it coming in handy, but it might be best suited for an external package/plugin in the future. What about trying an `.htaccess` file? Would that work for your use case?

**Comment by pkat** [comment]
@djfarrelly nope that won't work, since maildev doesn't run off of apache, its a node app (unless you proxy it). what about adding the node basic-auth package? easy to implement a simple 2 liner basic on a config option. https://www.npmjs.com/package/basic-auth

**Comment by djfarrelly** [comment]
I'm still not quite sure if this should be in the core project. I'm debating if it's outside of most users use cases. There are a couple higher priority items that I may work on in the near future, so I most likely won't hack on this, but I'm open to a pull request, sorry!

**Comment by djfarrelly** [comment]
Hey @pkat! A pull request was submitted and merged in today to add this feature. If you would like to use it today you can clone the project, or wait until I release version `0.10.0` later this week which will include that feature!
