### ISSUE TITLE
Export to eml

### ISSUE THREAD

**Issue by Ndrou** [djfarrelly/MailDev#51]
Hi all !

A new idea for you :)

The possibility to export one or more selected email to eml files.

Have a good day !

Bye !

**Comment by djfarrelly** [comment]
Thanks @Ndrou, that is a good idea! We're already saving the `.eml` in the temp directory, so this shouldn't take long to hack together. I'm traveling now, so my time might be limited, but would definitely like to add this to the project.

**Comment by djfarrelly** [comment]
Hey @Ndrou! Thanks for the idea, @damienbrz was able to submit a PR for this and we'll be releasing it in 0.9.0 soon :smile:

**Comment by Ndrou** [comment]
Good work guys ! ;)
