### ISSUE TITLE
Maildev on virtualbox

### ISSUE THREAD

**Issue by strauss69400** [djfarrelly/MailDev#56]
Hello, i work on virtualmachine.
On my vm, i installed debian7 

When i execute the command 'maildev',that work but the problem is that the console is blocked by maildev.

Is there a solution for this problem?

**Comment by djfarrelly** [comment]
Hey @strauss69400, thanks for reporting your issue!

When you mean "the console is blocked by maildev," do you mean that the process runs in your shell and you cannot execute any other commands? If this is the case, it's a feature I'd like to add at some point in the future (see #9), but to help you out right now you can install the npm package "forever" (https://github.com/foreverjs/forever) and use the full path to the maildev binary, see [this comment](https://github.com/djfarrelly/MailDev/issues/9#issuecomment-89364037) for more info!

**Comment by strauss69400** [comment]
Yes while the processus runs, i cannot execute other command.
Ok i will to see how to run forever.thank you

**Comment by strauss69400** [comment]
thank you very much.it works with forever.

but,Is there a solution for the service to be launched at system startup.

**Comment by djfarrelly** [comment]
@strauss69400 Oh, you may need to use a different approach to have it run on system startup automatically. I did a search and this project may meet your needs: https://github.com/chovy/node-startup
