### ISSUE TITLE
Google App Engine development server crashes MailDev

### ISSUE THREAD

**Issue by blupark** [djfarrelly/MailDev#68]
Hi, trying to test mail sending with Google App Engine (GAE) development server using MailDev and I get the following error after several tries of different configurations:

createCredentials() is deprecated, use tls.createSecureContext instead
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

GAE configuration details here: https://cloud.google.com/appengine/docs/python/tools/devserver#Python_Using_Mail
Any pointer for a workaround, or areas to look for fix would be appreciated.

**Comment by djfarrelly** [comment]
hey @blupark! What version of Node/io.js are you running on your dev server? I may need to test MailDev a bit more on 0.12.x and io.js 1.x

**Comment by blupark** [comment]
Hi, it is Node.js 0.12.4. What version did you test with/would recommend?
Thanks, Peter

**Comment by djfarrelly** [comment]
I've mostly been running MailDev w/ 0.10.x, but the tests are run against 0.10 and 0.12. I'm going to test it out against 0.12.4 locally to see if there are any issues I can find.

**Comment by djfarrelly** [comment]
This is working locally for me on 0.12.4. On a second look, this either may be an issue with [simplesmtp](https://github.com/andris9/simplesmtp) as it's an older, deprecated package that MailDev uses. This could also be an issue that the python dev server is requiring a secure connection to MailDev, but it's not running securely on https. I'm unfamiliar with Google app engine and that python dev server, do you think  the second one could be an issue?

**Comment by blupark** [comment]
Installed v0.10.33 and it works without a problem now. Not using secure
connection with the dev server (ie not configured/forced to use). It must
be some core library update that makes a difference in the underlying
networking/security protocol.

**Comment by djfarrelly** [comment]
Fixed with version 0.11.0
