### ISSUE TITLE
Emit sockets event on delete

### ISSUE THREAD

**Issue by cbdabner** [djfarrelly/MailDev#70]
Should _delete_ and _delete all_ emit events so that the frontend can react to deleted mail.

Currently, if one user deletes an item, other users still see it in the list and when they click on it they get shown the info landing page, and it's not intuitive that it's been deleted. They have to refresh the page to see the mail gone.

Maybe if a sockets event was emitted, the items could be removed from everyone's list.
Unless the user is actively looking at that item, in which case maybe you want some additional logic (the view that is currently shown can be left on screen until navigating elsewhere).

In fact, it looks like calling the Refresh logic is probably the desired result on delete.

Let me know your thoughts, and I might make a pull request later.

**Comment by djfarrelly** [comment]
This is a good point. I guess I've never used MailDev w/ multiple users/clients that needed to be in sync. I would definitely be open to a pull request that emitted an event to update the front-end!

Just for my own curiosity, how are you using MailDev that multiple users are using the interface simultaneously? I love to hear how people end up using the project :smile:

**Comment by cbdabner** [comment]
Previously, I worked in a private dev company where a hotfix was being developed for a client project, and the database contained some prod data. Emails were sent to public customers detailing scheduling of events, which wasn't pretty (not my work, although I'm sure I could have made the same mistake). So I setup MailCatcher at the time to help prevent that kind of thing.

Now, I'm working in the IT team (100 staff or so) for a larger public company who does some in-house development, but more often works on projects implementing various third-party software/solutions. There's a lot of processes etc that makes the potential for similar events less likely, but even so it's nice to avoid spamming your own inbox when projects are in dev/test.

I've setup MailDev in a central location, and have it starting up on a Windows Service (not allowed any Linux servers here). I haven't really spread the word much yet while I had a look at how it works. I haven't really looked into what occurs resource-wise etc.

The plan is to configure all projects in dev/test to use it, in conjunction with editing the dev/test servers' hosts file to remap any real SMTP to MailDev (in case someone misses the configuration). So in terms of multiple users, at any one time there could be up to maybe a dozen projects semi-actively sending mail. Additionally, I would expect the Test teams to get good usage out of it, being able to see the _exact_ intention of an application instead of finding some way to force an event to email themselves.

The Search box is probably good enough to differentiate between projects. It's pretty common for each project to use a custom _From_ address. Again, I haven't looked into the code, but it looks like when a new mail comes in, it adheres to the active search condition.

This also takes the spam away from MS Exchange, and avoids the (occasional) issues with Exchange blocking test mail as spam when mail frequency is too high (possibly due to bugs in applications etc).

**Comment by Seidr** [comment]
How's that? :)

**Comment by Seidr** [comment]
Sorry - mis-read the request. I'll add in the deleteAll event as well.

**Comment by Seidr** [comment]
@cbdabner Sorry - I also didn't notice that you said you'd do a pull request for this. Saw this on my break, and thought it was a great idea. As I hadn't done anything for a while, I jumped at the chance to get my hands dirty again..

**Comment by cbdabner** [comment]
@Seidr No worries at all! I wasn't getting around to it immediately, and I haven't actually played in node - it was more out of curiosity :smile:

Thanks for the help.

**Comment by djfarrelly** [comment]
Closed by  #71
