### ISSUE TITLE
MailDev preventing Node from exiting?

### ISSUE THREAD

**Issue by mramato** [djfarrelly/MailDev#75]
Hopefully there is a simple answer to my problem, but I couldn't find anything from searching past issues or the web.

I have a very simple Jasmine unit test set up where I programatically launch a MailDev server, send a few emails, validate they were received by MailDev and then shutdown.  However, the moment I introduce a `MailDev` server into my test, it prevents Node from exiting after the tests are complete.  Here's a reduced use case that causes the problem.  The "Do nothing" test passes, then the `Shut down` message gets printed, but it looks like MailDev still has active handles/requests open, preventing Node from exiting.

``` javascript
beforeAll(function (done) {
    mailServer = new MailDev({
        smtp: port,
        web: 8082,
        verbose: false
    });
    mailServer.listen(function (err) {
        if (err) {
            console.log(err);
            return done.fail();
        }
        console.log('Started up');
        done();
    });
});

afterAll(function (done) {
    mailServer.end(function () {
        console.log('Shut down');
        done();
    });
});

it("Do nothing", function (done) {
    done();
});
```

The moment I comment out the `listen` and `end` calls (still need to call `done`), the problem goes away, so I'm pretty sure the issue in in MailDev itself.  I hope I'm just doing something wrong on my end, but any help would be appreciated.  Thanks.

**Comment by sponte** [comment]
I see the same behaviour. Have you ever got it working @mramato?

**Comment by sponte** [comment]
After a quick look, the node process is not exiting because the web interface is still running after closing maildev server. I have added an option to disable it through configuration (```noWeb```). There is a pull request https://github.com/djfarrelly/MailDev/pull/165 waiting for approval but in the meantime I am using my fork directly.

```
npm install https://github.com/eu-evops/MailDev --save-dev
```

**Comment by mramato** [comment]
> I see the same behaviour. Have you ever got it working @mramato?

Unfortunately not, I gave up and just mocked the actual sending of mail in my tests. If your PR gets merged, I would definitely give it a shot and revisit the issue.  Thanks for looking more into it!

**Comment by sponte** [comment]
No worries. Just so you know it is working fine for me now with adding noWeb configuration option when instantiating new MailDev({ noWeb: true })
