### ISSUE TITLE
Auto-relay mode

### ISSUE THREAD

**Issue by Ndrou** [djfarrelly/MailDev#80]
Hi !

Idea:

Add the ability to configure maildev in auto relay mode. 
We could see in this case the emails that pass, but they would be transmitted to recipients.

Have a good day !

**Comment by brunowego** [comment]
+1

**Comment by Ndrou** [comment]
I will add to the pull request the ability to relay only certains emails with a system of include, exclude.

In the command line the ability to pass an option :
-auto-relay-include file.json -auto-relay-exclude file.json

The files will be as :

```javascript
[
  '*@gmail.com',
  'foo@bar.com'
]
```
