### ISSUE TITLE
email immediately closing after click

### ISSUE THREAD

**Issue by frsechet** [djfarrelly/MailDev#82]
Hi,

I'm using the docker version of maildev, and I have this weird issue that maildev catches the email but when I click on it, it opens for a millisecond and immediately closes again, so I can not see the email.

Email is plain text, nothing special about it... What is causing that?

Thanks!

**Comment by djfarrelly** [comment]
I'll need to try to reproduce this. It may be an issue with the websocket being updated. Has this issue persisted @frsechet?

**Comment by frsechet** [comment]
Yes. I have tried on Firefox and chrome on my Mac, everything latest stable version, and it happens almost every time. On the rare occasion I get to see one email, if I click on a second email it will fail, and the email list is cleared on every refresh.
I don't know why sometimes it works, as I don't do anything differently. I refresh the page 100 times and once in a while it will work., no matter whether I got the email before or after I refreshed.

**Comment by oktapodia** [comment]
Can you please create a little example to easily reproduce the problem?

**Comment by frsechet** [comment]
Oo are you kidding me? After 4 years, no, not really... Closing.

**Comment by oktapodia** [comment]
Sorry I'm trying to clean up the issues on this project and you may want to share your thought even after 4 years ;)

**Comment by frsechet** [comment]
I certainly hope I found a solution, one way or another... :-)
But I am not using maildev currently and maybe it works perfectly now, I don't know!

Good luck!
