### ISSUE TITLE
Add off method

### ISSUE THREAD

**Issue by drizgolovicha** [djfarrelly/MailDev#90]
Right now there is no possibility to add multiple listeners, I mean you can do it, but will be truly nice to add "off" method, to detach particular listener.

**Comment by djfarrelly** [comment]
Hey @drizgolovicha! There are two ways to remove listeners: `removeListener` and `removeAllListeners`. I must have missed adding them to the documentation :+1: 

Source: https://github.com/djfarrelly/MailDev/blob/master/lib/mailserver.js#L402-L403
