### ISSUE TITLE
Tag docker images

### ISSUE THREAD

**Issue by yrn1** [djfarrelly/MailDev#94]
Hi,

Can you tag the maildev docker images in the Docker Hub with a specific version number instead of only latest? Thanks!

**Comment by djfarrelly** [comment]
I'll try to change this flow when working on #95

**Comment by djfarrelly** [comment]
Hey @yrn1,
I've just pushed a new image w/ the tag `0.12.1` from now on I'll try to tag each release on Docker Hub: https://hub.docker.com/r/djfarrelly/maildev/tags/

Thanks!

**Comment by yrn1** [comment]
Thank you!
