### ISSUE TITLE
Docker build failing due to deprecated base image

### ISSUE THREAD

**Issue by amurf** [djfarrelly/MailDev#95]
The 'google/nodejs-runtime' image has been deprecated. See here https://hub.docker.com/r/google/nodejs-runtime/

To fix this you'll need to update your Dockerfile to be 'FROM node:onbuild'

You'll also need to update the entry CMD to be /usr/src/app/bin/maildev as that will change with the new base image.

**Comment by djfarrelly** [comment]
Thanks for this @amurf - the base image definitely needs to be updated. I'm thinking the project could use [this base image](https://hub.docker.com/r/library/node/) and get it working for Node 5.x. This is the top priority task for MailDev - Hoping to free up some time soon to knock this out, but if anyone wants to take a crack at a new `Dockerfile` the help is welcome :+1:

**Comment by djfarrelly** [comment]
Hey @amurf! I just updated the `Dockerfile` with a new base image. Sadly the overall image size is a lot larger, but it's back to working! This should show up on Docker hub very soon!
