### ISSUE TITLE
Unable to send 100 mails

### ISSUE THREAD

**Issue by MarcelPitch** [djfarrelly/MailDev#96]
Hi,

When I try to send 100 mails, I get this error : 

```
Error: Invalid greeting from server:
451 ESMTP MailEnable Service temporarily refused connection at 11/27/15 11:25:27 from IP (2.13.169.206) because the server is too busy.
at SMTPConnection._actionGreeting (/opt/apps/maildev/node_modules/smtp-connection/src/smtp-connection.js:611:23)
at SMTPConnection._processResponse (/opt/apps/maildev/node_modules/smtp-connection/src/smtp-connection.js:511:16)
at SMTPConnection._onData (/opt/apps/maildev/node_modules/smtp-connection/src/smtp-connection.js:357:10)
at Socket.EventEmitter.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:159:16)
at Socket.Readable.push (_stream_readable.js:126:10)
at TCP.onread (net.js:514:20)
```

Maybe MailDev cannot send so many mails ?

Thanks & have a nice day !

**Comment by donut87** [comment]
This is not exactly a MailDev problem, but an issue with the underlying
smtp-connection lib

On 27 November 2015 at 11:44, MarcelPitch <notifications@github.com> wrote:

> Hi,
>
> When I try to send 100 mails, I get this error :
>
> Error: Invalid greeting from server:
> 451 ESMTP MailEnable Service temporarily refused connection at 11/27/15 11:25:27 from IP (2.13.169.206) because the server is too busy.
> at SMTPConnection._actionGreeting (/opt/apps/maildev/node_modules/smtp-connection/src/smtp-connection.js:611:23)
> at SMTPConnection._processResponse (/opt/apps/maildev/node_modules/smtp-connection/src/smtp-connection.js:511:16)
> at SMTPConnection._onData (/opt/apps/maildev/node_modules/smtp-connection/src/smtp-connection.js:357:10)
> at Socket.EventEmitter.emit (events.js:107:17)
> at readableAddChunk (_stream_readable.js:159:16)
> at Socket.Readable.push (_stream_readable.js:126:10)
> at TCP.onread (net.js:514:20)
>
> Maybe MailDev cannot send so many mails ?
>
> Thanks & have a nice day !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djfarrelly/MailDev/issues/96>.
>



-- 
“Empty your mind, be formless, shapeless - like water. Now you put water
into a cup, it becomes the cup, you put water into a bottle, it becomes the
bottle, you put it in a teapot, it becomes the teapot. Now water can flow
or it can crash. Be water, my friend.” - Bruce Lee
