### ISSUE TITLE
Emails with <base> break embedded images

### ISSUE THREAD

**Issue by Arcnor** [djfarrelly/MailDev#97]
Related to #69 , if the email contains a <base> tag on its head, the images will not show. For example:

```html
<html>
<head><base href="http://example.com"/></head>
<body>
<img src="/email/cGVlFdin/attachment/myImage.png"/>
</body>
</html>
```

That's the HTML generated by MailDev, which looks correct, except that the image will be accessed at `"http://example.com/email/cGVlFdin/attachment/myImage.png"` instead of `"http://localhost:1080/email/cGVlFdin/attachment/myImage.png"`

**Comment by Soullivaneuh** [comment]
@Arcnor Just for curiosity, does the `base` tag work on every email platform?

**Comment by Arcnor** [comment]
AFAIK it does, we've been using it for a long time now.
